//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNotification
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public int cedula { get; set; }
        public string apellidos { get; set; }
        public string nombres { get; set; }
        public string sn_habilitado { get; set; }
        public Nullable<bool> genero { get; set; }
    }
}
